import sgMail from '@sendgrid/mail';
import { HandoverDossier } from './openai';
import { Conversation, Message } from '@shared/schema';

// Initialize SendGrid with the API key
sgMail.setApiKey(process.env.SENDGRID_API_KEY || '');

interface SendHandoverEmailParams {
  toEmail: string;
  fromEmail: string;
  dossier: HandoverDossier;
}

interface SendConversationSummaryParams {
  toEmail: string;
  fromEmail: string;
  conversation: Conversation;
  messages: Message[];
  dealershipName: string;
}

/**
 * Sends a conversation summary email to the specified recipient
 */
export async function sendConversationSummary({
  toEmail,
  fromEmail,
  conversation,
  messages,
  dealershipName
}: SendConversationSummaryParams): Promise<boolean> {
  try {
    // Format the conversation history as HTML
    const conversationHtml = messages
      .map(msg => {
        const role = msg.isFromCustomer ? 'Customer' : 'Rylie';
        const timestamp = new Date(msg.createdAt).toLocaleString();
        return `
          <div style="margin-bottom: 12px;">
            <strong>${role}</strong> <span style="color: #888; font-size: 0.9em;">${timestamp}</span>
            <div style="margin-left: 20px; margin-top: 4px;">${msg.content}</div>
          </div>
        `;
      })
      .join('');
    
    // Determine conversation status color
    let statusColor = '#4CAF50'; // Green for active
    if (conversation.status === 'waiting') {
      statusColor = '#FF9800'; // Orange for waiting
    } else if (conversation.status === 'escalated') {
      statusColor = '#F44336'; // Red for escalated
    } else if (conversation.status === 'completed') {
      statusColor = '#2196F3'; // Blue for completed
    }
    
    // Create email HTML with the conversation summary
    const emailHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Conversation Summary: ${conversation.customerName}</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 700px; margin: 0 auto; padding: 20px; }
          .header { background-color: #1a237e; color: white; padding: 15px; border-radius: 5px 5px 0 0; text-align: center; }
          .section { margin-bottom: 25px; border-bottom: 1px solid #eee; padding-bottom: 15px; }
          .section-title { font-size: 18px; font-weight: bold; margin-bottom: 10px; color: #1a237e; }
          .conversation { background-color: #f9f9f9; padding: 15px; border-radius: 5px; max-height: 500px; overflow-y: auto; }
          .footer { font-size: 14px; color: #777; margin-top: 30px; text-align: center; }
          .status-badge { display: inline-block; padding: 4px 8px; border-radius: 4px; color: white; font-weight: bold; background-color: ${statusColor}; }
          .customer-info { margin: 20px 0; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1 style="margin: 0;">Conversation Summary</h1>
            <p style="margin: 5px 0 0 0;">${dealershipName}</p>
          </div>
          
          <div class="section customer-info">
            <div class="section-title">Customer Information</div>
            <p><strong>Name:</strong> ${conversation.customerName}</p>
            <p><strong>Phone:</strong> ${conversation.customerPhone || 'Not provided'}</p>
            <p><strong>Email:</strong> ${conversation.customerEmail || 'Not provided'}</p>
            <p><strong>Status:</strong> <span class="status-badge">${conversation.status.toUpperCase()}</span></p>
            <p><strong>Started:</strong> ${new Date(conversation.createdAt).toLocaleString()}</p>
            <p><strong>Last Update:</strong> ${new Date(conversation.updatedAt).toLocaleString()}</p>
          </div>
          
          <div class="section">
            <div class="section-title">Context Information</div>
            <p><strong>Campaign:</strong> ${conversation.campaignContext || 'None'}</p>
            <p><strong>Inventory Context:</strong> ${conversation.inventoryContext || 'None'}</p>
            ${conversation.escalatedToUserId ? `<p><strong>Assigned To:</strong> User ID ${conversation.escalatedToUserId}</p>` : ''}
          </div>
          
          <div class="section">
            <div class="section-title">Conversation History (${messages.length} messages)</div>
            <div class="conversation">
              ${conversationHtml}
            </div>
          </div>
          
          <div class="footer">
            <p>This conversation summary was automatically generated by Rylie AI.</p>
            <p>To view this conversation in the dashboard, <a href="https://app.example.com/conversations/${conversation.id}">click here</a>.</p>
          </div>
        </div>
      </body>
      </html>
    `;
    
    // Send the email
    const msg = {
      to: toEmail,
      from: fromEmail,
      subject: `Conversation Summary: ${conversation.customerName} - ${dealershipName}`,
      text: `Conversation summary for ${conversation.customerName}. Status: ${conversation.status}. ${messages.length} messages.`,
      html: emailHtml,
    };
    
    await sgMail.send(msg);
    return true;
  } catch (error) {
    console.error('Error sending conversation summary email:', error);
    return false;
  }
}

/**
 * Sends the handover dossier to the specified sales representative via email
 */
export async function sendHandoverEmail({
  toEmail,
  fromEmail,
  dossier
}: SendHandoverEmailParams): Promise<boolean> {
  try {
    // Format the conversation history as HTML
    const conversationHtml = dossier.conversationHistory
      .map(msg => {
        const role = msg.role === 'customer' ? 'Customer' : 'Rylie';
        const timestamp = msg.timestamp ? new Date(msg.timestamp).toLocaleString() : '';
        return `
          <div style="margin-bottom: 12px;">
            <strong>${role}</strong> <span style="color: #888; font-size: 0.9em;">${timestamp}</span>
            <div style="margin-left: 20px; margin-top: 4px;">${msg.content}</div>
          </div>
        `;
      })
      .join('');

    // Format the key points as HTML list
    const keyPointsHtml = dossier.keyPoints
      .map(point => `<li>${point}</li>`)
      .join('');

    // Format the products of interest as HTML list
    const productsInterestedHtml = dossier.productsInterested
      .map(product => `<li>${product}</li>`)
      .join('');

    // Format engagement tips as HTML list
    const engagementTipsHtml = dossier.engagementTips
      .map(tip => `<li>${tip}</li>`)
      .join('');

    // Format closing strategies as HTML list
    const closingStrategiesHtml = dossier.closingStrategies
      .map(strategy => `<li>${strategy}</li>`)
      .join('');

    // Create a professional-looking email template for the dossier based on the provided format
    const emailHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Lead Handover: ${dossier.customerName}</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 700px; margin: 0 auto; padding: 20px; }
          .header { background-color: #1a237e; color: white; padding: 15px; border-radius: 5px 5px 0 0; text-align: center; }
          .pre-header { background-color: #f5f5f5; padding: 15px; text-align: center; font-style: italic; }
          .section { margin-bottom: 25px; border-bottom: 1px solid #eee; padding-bottom: 15px; }
          .section-title { font-size: 18px; font-weight: bold; margin-bottom: 10px; color: #1a237e; }
          .section-number { background-color: #1a237e; color: white; display: inline-block; width: 24px; height: 24px; border-radius: 50%; text-align: center; margin-right: 8px; }
          .conversation { background-color: #f9f9f9; padding: 15px; border-radius: 5px; max-height: 400px; overflow-y: auto; }
          .footer { font-size: 14px; color: #777; margin-top: 30px; text-align: center; font-style: italic; }
          ul { margin-top: 5px; }
          .contact-detail { margin: 5px 0; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="pre-header">
            <p>Lead Handover Notification: Human Engagement Required</p>
          </div>
          
          <div class="header">
            <h1 style="margin: 0;">Lead Handover: ${dossier.customerName}</h1>
            <p style="margin: 5px 0 0 0;">${dossier.dealershipName}</p>
          </div>
          
          <p style="font-style: italic; text-align: center; margin: 20px 0;">
            We have a promising lead requiring your expertise to finalize the details for a potential sale. 
            Below you'll find comprehensive information about the lead to prepare for your interaction. 
            Please review the details carefully to tailor your approach effectively.
          </p>
          
          <div class="section">
            <div class="section-title"><span class="section-number">1</span> Lead Identification</div>
            <p><strong>Name:</strong> ${dossier.customerName}</p>
            <p class="contact-detail"><strong>Contact Details:</strong> 
              ${dossier.contactDetails.email ? `Email - ${dossier.contactDetails.email}` : ''}
              ${dossier.contactDetails.email && dossier.contactDetails.phone ? ', ' : ''}
              ${dossier.contactDetails.phone ? `Phone - ${dossier.contactDetails.phone}` : ''}
            </p>
            <p><strong>Products Interested In:</strong></p>
            <ul>${productsInterestedHtml}</ul>
            <p><strong>Likely Purchase Date/Timeline:</strong> ${dossier.purchaseTimeline}</p>
          </div>
          
          <div class="section">
            <div class="section-title"><span class="section-number">2</span> Conversation Summary</div>
            <p><strong>Key Points:</strong></p>
            <ul>${keyPointsHtml}</ul>
            <p><strong>Lead's Intent:</strong> ${dossier.leadIntent}</p>
          </div>
          
          <div class="section">
            <div class="section-title"><span class="section-number">3</span> Relationship Building Information</div>
            <p><strong>Personal Insights:</strong> ${dossier.personalInsights}</p>
            <p><strong>Communication Style:</strong> ${dossier.communicationStyle}</p>
          </div>
          
          <div class="section">
            <div class="section-title"><span class="section-number">4</span> Sales Strategies</div>
            <p><strong>Engagement Tips:</strong></p>
            <ul>${engagementTipsHtml}</ul>
            <p><strong>Closing Strategies:</strong></p>
            <ul>${closingStrategiesHtml}</ul>
          </div>
          
          <div class="section">
            <div class="section-title">Conversation History</div>
            <div class="conversation">
              ${conversationHtml}
            </div>
          </div>
          
          <div class="footer">
            <p>Your adept skills in managing client relations and closing deals can undoubtedly make a significant difference here. Wishing you the best in this engagement!</p>
          </div>
        </div>
      </body>
      </html>
    `;

    // Send the email with the dossier
    const msg = {
      to: toEmail,
      from: fromEmail,
      subject: `Lead Handover: ${dossier.customerName} - ${dossier.dealershipName}`,
      text: `Lead handover for ${dossier.customerName} from ${dossier.dealershipName}. Please view in HTML format for a better experience.`,
      html: emailHtml,
    };

    await sgMail.send(msg);
    return true;
  } catch (error) {
    console.error('Error sending handover email:', error);
    return false;
  }
}