import sgMail from '@sendgrid/mail';
import { HandoverDossier } from './openai';

// Initialize SendGrid with the API key
sgMail.setApiKey(process.env.SENDGRID_API_KEY || '');

interface SendHandoverEmailParams {
  toEmail: string;
  fromEmail: string;
  dossier: HandoverDossier;
}

/**
 * Sends the handover dossier to the specified sales representative via email
 */
export async function sendHandoverEmail({
  toEmail,
  fromEmail,
  dossier
}: SendHandoverEmailParams): Promise<boolean> {
  try {
    // Format the conversation history as HTML
    const conversationHtml = dossier.conversationHistory
      .map(msg => {
        const role = msg.role === 'customer' ? 'Customer' : 'Rylie';
        const timestamp = msg.timestamp ? new Date(msg.timestamp).toLocaleString() : '';
        return `
          <div style="margin-bottom: 12px;">
            <strong>${role}</strong> <span style="color: #888; font-size: 0.9em;">${timestamp}</span>
            <div style="margin-left: 20px; margin-top: 4px;">${msg.content}</div>
          </div>
        `;
      })
      .join('');

    // Format the customer priorities as HTML list
    const prioritiesHtml = dossier.customerPriorities
      .map(priority => `<li>${priority}</li>`)
      .join('');

    // Format the vehicle interests as HTML list
    const vehicleInterestsHtml = dossier.vehicleInterests
      .map(vehicle => `<li>${vehicle}</li>`)
      .join('');

    // Create a professional-looking email template for the dossier
    const emailHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Conversation Handover: ${dossier.customerName}</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 700px; margin: 0 auto; padding: 20px; }
          .header { background-color: #1a237e; color: white; padding: 15px; border-radius: 5px 5px 0 0; }
          .section { margin-bottom: 25px; border-bottom: 1px solid #eee; padding-bottom: 15px; }
          .section-title { font-size: 18px; font-weight: bold; margin-bottom: 10px; color: #1a237e; }
          .conversation { background-color: #f9f9f9; padding: 15px; border-radius: 5px; }
          .footer { font-size: 14px; color: #777; margin-top: 30px; }
          ul { margin-top: 5px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1 style="margin: 0;">Lead Handover: ${dossier.customerName}</h1>
            <p style="margin: 5px 0 0 0;">${dossier.dealershipName}</p>
          </div>
          
          <div class="section">
            <div class="section-title">Lead Summary</div>
            <p>${dossier.conversationSummary}</p>
          </div>
          
          <div class="section">
            <div class="section-title">Customer Personality</div>
            <p>${dossier.customerPersonality}</p>
          </div>
          
          <div class="section">
            <div class="section-title">Customer Priorities</div>
            <ul>${prioritiesHtml}</ul>
          </div>
          
          <div class="section">
            <div class="section-title">Vehicle Interests</div>
            <ul>${vehicleInterestsHtml}</ul>
          </div>
          
          <div class="section">
            <div class="section-title">Suggested Approach</div>
            <p>${dossier.suggestedApproach}</p>
          </div>
          
          <div class="section">
            <div class="section-title">Conversation History</div>
            <div class="conversation">
              ${conversationHtml}
            </div>
          </div>
          
          <div class="footer">
            <p>This handover was automatically generated by Rylie AI to help you close this lead.</p>
          </div>
        </div>
      </body>
      </html>
    `;

    // Send the email with the dossier
    const msg = {
      to: toEmail,
      from: fromEmail,
      subject: `Lead Handover: ${dossier.customerName} - ${dossier.dealershipName}`,
      text: `Lead handover for ${dossier.customerName} from ${dossier.dealershipName}. Please view in HTML format for a better experience.`,
      html: emailHtml,
    };

    await sgMail.send(msg);
    return true;
  } catch (error) {
    console.error('Error sending handover email:', error);
    return false;
  }
}